### ISSUE TITLE
NameError: name 'basestring' is not defined

### ISSUE THREAD

**Issue by ktsakalozos** [juju-solutions/reactive-base-layer#19]
Placing the apt_install in the bootstrap throws the error below.
```
unit-gbuilder-0[994]: 2016-01-12 13:24:10 INFO unit.gbuilder/0.install logger.go:40 Traceback (most recent call last):
unit-gbuilder-0[994]: 2016-01-12 13:24:10 INFO unit.gbuilder/0.install logger.go:40   File "/var/lib/juju/agents/unit-gbuilder-0/charm/hooks/install", line 8, in <module>
unit-gbuilder-0[994]: 2016-01-12 13:24:10 INFO unit.gbuilder/0.install logger.go:40     bootstrap_charm_deps()
unit-gbuilder-0[994]: 2016-01-12 13:24:10 INFO unit.gbuilder/0.install logger.go:40   File "lib/charms/bootstrap.py", line 12, in bootstrap_charm_deps
unit-gbuilder-0[994]: 2016-01-12 13:24:10 INFO unit.gbuilder/0.install logger.go:40     apt_install(['python3-pip', 'python3-yaml'])
unit-gbuilder-0[994]: 2016-01-12 13:24:10 INFO unit.gbuilder/0.install logger.go:40   File "lib/charms/bootstrap.py", line 36, in apt_install
unit-gbuilder-0[994]: 2016-01-12 13:24:10 INFO unit.gbuilder/0.install logger.go:40     if isinstance(packages, basestring):
unit-gbuilder-0[994]: 2016-01-12 13:24:10 INFO unit.gbuilder/0.install logger.go:40 NameError: name 'basestring' is not defined
unit-gbuilder-0[994]: 2016-01-12 13:24:10 ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1
```
Quick fix that worked for me is to comment out the 
    #if isinstance(packages, basestring):
    #    packages = [packages]

**Comment by ktsakalozos** [comment]
Thank you! You are fast!

**Comment by mbruzek** [comment]
I also encountered this issue, thanks for fixing this marco/cory!
